pipeline {
    agent {
        label 'agent88'
    }

    options {
        buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '20')
    }

    triggers {
        cron '*/10 * * * *'
    }

    stages {
        stage('Disk Usage') {
            steps {
                sh "df -h"
            }
        }
    }
}
