pipeline {
    agent {
        label 'agent88'
    }

    triggers {
    cron '*/10 * * * *'
    }

    stages {
        stage('Disk Usage') {
            steps {
                sh "df -h"
            }
        }
    }
}
