pipeline {
    agent {
        label 'agent88'
    }

    options {
        timeout(10)
    }

    stages {
        stage('Make Folder') {
            steps {
                sh "mkdir /home/core"
            }
        }
    }
}
