pipeline {
    agent {
        label 'agent88'
    }

    options {
        timeout(10)
    }

    stages {
        stage('Make Directory') {
            steps {
                sh "rm -rf /home/core" // To make sure directory does not exist!
                sh "mkdir /home/core"
            }
        }
    }
}
